In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.font_manager as fm
from pandas import Series, DataFrame

# 시각화 라이브러리
import matplotlib.pyplot as plt

# 그래프를 주피터 노트북에 그리기 위한 설정
%matplotlib inline

# 소수점 3자리까지 표시
%precision 3


Bad key text.latex.preview in file /Users/kwak-yejin/opt/anaconda3/envs/deeplearning/lib/python3.8/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key mathtext.fallback_to_cm in file /Users/kwak-yejin/opt/anaconda3/envs/deeplearning/lib/python3.8/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key savefig.jpeg_quality in file /Users/kwak-yejin/opt/anaconda3/envs/deeplearning/lib/python3.8/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, lin

'%.3f'

In [2]:
result1 = pd.read_csv("result1_imputed.csv", sep=",")
result2 = pd.read_csv("result2_imputed.csv", sep=",")
result3 = pd.read_csv("result3_imputed.csv", sep=",")

In [3]:
result1.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8279 entries, 0 to 8278
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   BMI                    8279 non-null   float64
 1   Weight                 8279 non-null   float64
 2   age                    8279 non-null   float64
 3   bending_forward        8279 non-null   float64
 4   body_fat               8279 non-null   float64
 5   diastolic_bp           8279 non-null   float64
 6   grip_power             8279 non-null   float64
 7   height                 8279 non-null   float64
 8   label                  8279 non-null   int64  
 9   measure_time           8279 non-null   float64
 10  sex                    8279 non-null   float64
 11  sit_up                 8279 non-null   float64
 12  step_inspection        8279 non-null   float64
 13  step_recover_time      8279 non-null   float64
 14  systolic_bp            8279 non-null   float64
 15  scor

In [4]:
result1[result1["exercise_prescription"].isnull()].index

Int64Index([   9,   10,   23,   25,   29,   34,   38,   42,   48,   55,
            ...
            8200, 8227, 8239, 8243, 8256, 8261, 8262, 8267, 8271, 8278],
           dtype='int64', length=1164)

In [5]:
7115+1164

8279

In [6]:
result1 = result1.drop(result1[result1["exercise_prescription"].isnull()].index, axis=0)
result1 = result1.reset_index(drop=True)
result1

BMI  Weight   age  bending_forward  body_fat  diastolic_bp  grip_power  \
0     19.3    43.2  49.0            -10.0      36.0          88.0        11.1   
1     18.5    48.7  47.0             -3.0      21.5         100.0         6.0   
2     22.5    66.3  26.0             -0.2      20.4          77.0        22.4   
3     18.9    52.5  38.0             16.7      14.5          89.0        10.3   
4     22.6    59.2  36.0            -15.0      28.7          79.0        12.9   
...    ...     ...   ...              ...       ...           ...         ...   
7110  28.9    80.6  28.0            -20.0      36.5          71.0        16.4   
7111  18.5    50.8  41.0            -20.0      31.4          99.0         9.5   
7112  21.7    47.2  38.0            -20.0      33.2          54.0        11.3   
7113  34.8    71.2  41.0            -20.0      49.4          83.0        11.3   
7114  24.5    74.3  34.0            -20.0      21.7          52.0        23.8   

      height  label  measure_time  sex  sit_up  step_inspection  \
0      149.8      1        2019.0  1.0     6.0             47.4   
1      162.4      1        2019.0  1.0    13.0             47.4   
2      171.6      1        2019.0  1.0    15.0             46.2   
3      166.8      1        2019.0  1.0    10.0             48.9   
4      161.8      1        2019.0  1.0     7.0             51.4   
...      ...    ...           ...  ...     ...              ...   
7110   167.0      1        2021.0  1.0     2.0             39.8   
7111   165.6      1        2021.0  1.0     1.0             42.3   
7112   147.6      1        2021.0  1.0     2.0             42.0   
7113   143.0      1        2021.0  1.0     2.0             35.0   
7114   174.3      1        2021.0  1.0    11.0             45.5   

      step_recover_time  systolic_bp    scores  match_id  record_id  \
0                  89.0        133.0  0.991376         0    2884332   
1                  91.0        139.0  0.992535         1    2884333   
2                 112.0        122.0  0.898405         2    2884334   
3                  92.0        134.0  0.967028         3    2884335   
4                  66.0        127.0  0.994139         4    2884336   
...                 ...          ...       ...       ...        ...   
7110              125.0        116.0  0.997637      8273    2892605   
7111              130.0        152.0  0.998316      8274    2892606   
7112              123.0        105.0  0.994886      8275    2892607   
7113              116.0        126.0  0.999538      8276    2892608   
7114               88.0        129.0  0.931370      8277    2892609   

                                  exercise_prescription  
0     본운동:한발 연속 뛰기,뒤꿈치 높이들어 뛰기,무릎 높이 들어 뛰기,점프하며 뛰기,메...  
1     준비운동:정적 스트레칭  루틴프로그램,동적 스트레칭 루틴프로그램,몸통 들어올리기,팔...  
2     준비운동:동적 스트레칭 루틴프로그램 / 본운동:합장하여 앞으로 숙이기,허리숙여 양팔...  
3     준비운동:전신 루틴 스트레칭,한발 앞으로 내밀고 앉았다 일어서기,서서 상체 일으키기...  
4                                    본운동:동적 스트레칭 루틴프로그램  
...                                                 ...  
7110                                           준비운동:달리기  
7111         준비운동:줄넘기 운동,앉았다 일어서기,엉덩이 늘리기,짐볼 운동  루틴프로그램  
7112  준비운동:하지 루틴 스트레칭1,하지 루틴 스트레칭2,전신 루틴 스트레칭,유산소 운동...  
7113  준비운동:무릎굽혀 원 그리기,네발 걷기,다리 들어올리기,고양이 자세,옆구리 스트레칭...  
7114  준비운동:동적 스트레칭 루틴프로그램 / 본운동:웨이트 트레이닝  루틴프로그램,발 바...  

[7115 rows x 19 columns]

In [7]:
result1.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7115 entries, 0 to 7114
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   BMI                    7115 non-null   float64
 1   Weight                 7115 non-null   float64
 2   age                    7115 non-null   float64
 3   bending_forward        7115 non-null   float64
 4   body_fat               7115 non-null   float64
 5   diastolic_bp           7115 non-null   float64
 6   grip_power             7115 non-null   float64
 7   height                 7115 non-null   float64
 8   label                  7115 non-null   int64  
 9   measure_time           7115 non-null   float64
 10  sex                    7115 non-null   float64
 11  sit_up                 7115 non-null   float64
 12  step_inspection        7115 non-null   float64
 13  step_recover_time      7115 non-null   float64
 14  systolic_bp            7115 non-null   float64
 15  scor

In [8]:
result1["exercise_prescription"]

0       본운동:한발 연속 뛰기,뒤꿈치 높이들어 뛰기,무릎 높이 들어 뛰기,점프하며 뛰기,메...
1       준비운동:정적 스트레칭  루틴프로그램,동적 스트레칭 루틴프로그램,몸통 들어올리기,팔...
2       준비운동:동적 스트레칭 루틴프로그램 / 본운동:합장하여 앞으로 숙이기,허리숙여 양팔...
3       준비운동:전신 루틴 스트레칭,한발 앞으로 내밀고 앉았다 일어서기,서서 상체 일으키기...
4                                      본운동:동적 스트레칭 루틴프로그램
                              ...                        
7110                                             준비운동:달리기
7111           준비운동:줄넘기 운동,앉았다 일어서기,엉덩이 늘리기,짐볼 운동  루틴프로그램
7112    준비운동:하지 루틴 스트레칭1,하지 루틴 스트레칭2,전신 루틴 스트레칭,유산소 운동...
7113    준비운동:무릎굽혀 원 그리기,네발 걷기,다리 들어올리기,고양이 자세,옆구리 스트레칭...
7114    준비운동:동적 스트레칭 루틴프로그램 / 본운동:웨이트 트레이닝  루틴프로그램,발 바...
Name: exercise_prescription, Length: 7115, dtype: object

In [9]:
for i in range(len(result1)):
    result1['exercise_prescription'][i] = result1['exercise_prescription'][i].replace(" " , "").replace("준비운동" , "준비운동").replace("/본운동" , "|본운동").replace("/마무리운동" , "|마무리운동")
    result1['exercise_prescription'][i] = result1['exercise_prescription'][i].replace("/" , "").replace("|" , "/")

In [10]:
result1['exercise_prescription'][5]

'준비운동:정적스트레칭루틴프로그램/본운동:앞굽이앉았다일어서기,측면팔대고버티기,상체앞으로숙이기,손뻗어윗몸일으키기/마무리운동:짝스트레칭루틴프로그램'

In [11]:
num = list()
for i in range (len(result1)):
    num.append(len(result1['exercise_prescription'][i].replace(" " , "").split('/')))

In [12]:
set(num)

{1, 2, 3}

In [13]:
len(num)

7115

In [14]:
(result1['exercise_prescription'][36].replace(" " , "").split('/'))

['준비운동:깍지끼고상체숙이기,목스트레칭,등어깨뒤쪽스트레칭,어깨뒤쪽스트레칭,아래팔스트레칭',
 '본운동:몸통들어올리기,소파를이용한윗몸올리기,엎드려버티기,옆으로누워버티기,네발기기자세로팔다리들기,엎드려서팔다리들기',
 '마무리운동:깍지끼고상체숙이기,목스트레칭,등어깨뒤쪽스트레칭,아래팔스트레칭,넙다리안쪽스트레칭,허리스트레칭']

In [15]:
prepare = list()
main = list()
end = list()
for i in range (len(result1)):
    if len(result1['exercise_prescription'][i].replace(" " , "").split('/')) == 1:
        if result1['exercise_prescription'][i].replace(" " , "").split('/')[0][:4] == '준비운동':
            prepare.append(result1['exercise_prescription'][i].replace(" " , "").split('/')[0][5:].split(','))
            main.append([])
            end.append([])
        elif result1['exercise_prescription'][i].replace(" " , "").split('/')[0][:3] == '본운동':
            main.append(result1['exercise_prescription'][i].replace(" " , "").split('/')[0][4:].split(','))
            prepare.append([])
            end.append([])
        else:
            end.append(result1['exercise_prescription'][i].replace(" " , "").split('/')[0][6:].split(','))
            prepare.append([])
            main.append([])

            
    if len(result1['exercise_prescription'][i].replace(" " , "").split('/')) == 2:
        if result1['exercise_prescription'][i].replace(" " , "").split('/')[0][:4] == '준비운동':
            prepare.append(result1['exercise_prescription'][i].replace(" " , "").split('/')[0][5:].split(','))
            if result1['exercise_prescription'][i].replace(" " , "").split('/')[1][:3] == '본운동':
                main.append(result1['exercise_prescription'][i].replace(" " , "").split('/')[0][4:].split(','))
                end.append([])
            else:
                end.append(result1['exercise_prescription'][i].replace(" " , "").split('/')[0][6:].split(','))
                main.append([])
                
        else:
            main.append(result1['exercise_prescription'][i].replace(" " , "").split('/')[0][4:].split(','))
            end.append(result1['exercise_prescription'][i].replace(" " , "").split('/')[1][6:].split(','))
            prepare.append([])
            
    if len(result1['exercise_prescription'][i].replace(" " , "").split('/')) == 3:
        prepare.append(result1['exercise_prescription'][i].replace(" " , "").split('/')[0][5:].split(','))
        main.append(result1['exercise_prescription'][i].replace(" " , "").split('/')[1][4:].split(','))       
        end.append(result1['exercise_prescription'][i].replace(" " , "").split('/')[2][6:].split(','))

In [16]:
prepare

[[],
 ['정적스트레칭루틴프로그램',
  '동적스트레칭루틴프로그램',
  '몸통들어올리기',
  '팔굽혀펴기',
  '팔다리교차버티기',
  '윗몸일으키기',
  '앉았다일어서기',
  '버피테스트',
  '걷기',
  '조깅',
  '자전거타기'],
 ['동적스트레칭루틴프로그램'],
 ['전신루틴스트레칭', '한발앞으로내밀고앉았다일어서기', '서서상체일으키기', '엎드려버티기', '누워서엉덩이들어올리기', '팔굽혀펴기'],
 [],
 ['정적스트레칭루틴프로그램'],
 ['한발앞굽이팔위로뻗어가슴내밀기',
  '다리꼬아상체앞으로숙이기',
  '다리벌려옆으로상체숙이기',
  '다리모아상체숙이기',
  '다리벌려앞으로상체숙이기'],
 ['동적스트레칭루틴프로그램'],
 ['앉아서밴드잡고몸통돌리기', '밴드잡고몸통옆으로굽히기', '바벨들어올리기'],
 ['하지루틴스트레칭1', '상지루틴스트레칭'],
 ['다리벌려옆으로상체숙이기',
  '다리벌려앞으로상체숙이기',
  '발목얹고다리잡아당기기',
  '다리모아상체숙이기',
  '한발뒤로빼고앞으로굽히기',
  '앉아서옆구리늘려주기'],
 ['발목얹고다리잡아당기기', '누워서굽힌다리펴기', '무릎굽혀가슴닿기', '한발뒤로빼고앞으로굽히기'],
 ['관절염을위한스트레칭'],
 ['허리스트레칭', '조깅', '앉았다일어서기'],
 ['동적스트레칭루틴프로그램', '다리벌려옆으로상체숙이기', '다리벌려앞으로상체숙이기', '누워서굽힌다리펴기'],
 ['깍지끼고상체숙이기', '목스트레칭', '회전근개스트레칭', '어깨스트레칭', '넙다리앞쪽스트레칭', '대퇴사두근스트레칭'],
 [],
 [],
 ['왕복달리기', '제자리뛰기', '박스옆으로번갈아뛰기'],
 [],
 ['발목얹고다리잡아당기기', '누워서굽힌다리펴기', '무릎굽혀가슴닿기', '한발뒤로빼고앞으로굽히기'],
 ['동적스트레칭루틴프로그램'],
 [],
 ['무릎굽혀가슴닿기',
  '발바닥마주대고끌어당기기',
  '발목얹고다리잡아당기기',
  '다리벌려앞으로상체숙이기',
  '다

In [17]:
len(prepare)

7115

In [18]:
for i in main:
    if i:
        if i[0][:1]==':':
            i[0] = i[0][1:]

In [19]:
main

[['한발연속뛰기',
  '뒤꿈치높이들어뛰기',
  '무릎높이들어뛰기',
  '점프하며뛰기',
  '메디신볼운동루틴프로그램',
  '짐볼운동루틴프로그램',
  '머리위로볼돌리기',
  '볼잡고몸통기울이기',
  '허리감아볼돌리기'],
 [],
 ['합장하여앞으로숙이기', '허리숙여양팔돌리기', '몸통스트레칭', '옆구리스트레칭', '엎드려상체들어올리기', '다리모아무릎누르기'],
 [],
 ['동적스트레칭루틴프로그램'],
 ['앞굽이앉았다일어서기', '측면팔대고버티기', '상체앞으로숙이기', '손뻗어윗몸일으키기'],
 ['팔굽혀펴기',
  '엎드려팔로걷기',
  '아령앞으로들어올리기',
  '의자잡고팔뒤로굽히기',
  '밴드앞옆으로들어올리기',
  '엎드려팔대고버티기',
  '앉았다일어서기',
  '다리앞뒤로벌려굽혔다펴기',
  '교차다리굽히기'],
 ['순간반응콘찍기',
  '앉았다일어나며점프하기',
  '다리뻗어점프하기',
  '좌우양발모아점프하기',
  '한발로점프하기',
  '연속상향점프하기',
  '좌우이동하며팔굽혀펴기',
  '팔굽혀펴기후점프하기',
  '크게다리벌려교차뛰기',
  '뒷발교차뛰기'],
 ['짐볼이용근력운동루틴프로그램', '의자이용근력운동루틴프로그램', '머신이용근력운동루틴프로그램'],
 ['팔굽혀펴기', '윗몸일으키기', '발바꿔뛰기', '크런치사이클'],
 ['윗몸말아올리기',
  '앉았다일어서기',
  '엎드려팔대고버티기',
  '발뒤꿈치들어올리기',
  '엎드려팔로걷기',
  '밴드앞옆으로들어올리기',
  '밴드어깨뒤로들어올리기',
  '팔구부려등모으기',
  '다리앞뒤로벌려굽혔다펴기',
  '옆으로팔대고버티기',
  '무릎굽혀엉덩이들어올리기',
  '옆으로누워무릎벌리기',
  '머리뒤로깍지끼고상체숙이기'],
 ['앉았다일어서기', '팔굽혀펴기', '엎드려팔로걷기', '앉아서엉덩이들고이동하기'],
 ['관절염을위한스트레칭'],
 [],
 ['앉았다일어서기',
  '다리앞뒤로벌려굽혔다펴기',
  '앉아서밴드당기기',
  '앞발의자

In [20]:
len(main)

7115

In [21]:
for i in end:
    if i:
        if i[0][:1]==':':
            i[0] = i[0][1:]

In [22]:
end

[[],
 [],
 ['정적스트레칭루틴프로그램'],
 [],
 [],
 ['짝스트레칭루틴프로그램'],
 ['무릎굽혀가슴닿기',
  '앉아서한발앞으로굽히기',
  '앉아윗몸앞으로굽히기',
  '한발뒤로빼고앞으로굽히기',
  '누워서굽힌다리펴기',
  '엎드려어깨늘리기'],
 ['정적스트레칭루틴프로그램'],
 ['다리들어옆으로올리기', '무릎굽혀원그리기'],
 ['전신루틴스트레칭'],
 ['다리벌려옆으로상체숙이기',
  '다리벌려앞으로상체숙이기',
  '누워서굽힌다리펴기',
  '다리모아상체숙이기',
  '발바닥마주대고끌어당기기',
  '앉아서한발앞으로굽히기',
  '앉아윗몸앞으로굽히기',
  '앉아서옆구리늘려주기'],
 ['다리모아뒤로눕기', '활자세', '무릎대고상체뒤로젖히기', '엎드려어깨늘리기'],
 [],
 [],
 ['정적스트레칭루틴프로그램', '다리꼬아상체앞으로숙이기', '엎드려교차발잡아당기기', '무릎대고옆으로기울이기'],
 [],
 [],
 [],
 [],
 [],
 ['다리모아뒤로눕기', '활자세', '무릎대고상체뒤로젖히기', '엎드려어깨늘리기'],
 [],
 [],
 ['발목얹고다리잡아당기기', '한발앞굽이팔위로뻗어가슴내밀기'],
 [],
 ['정적스트레칭루틴프로그램'],
 ['요가및필라테스루틴프로그램'],
 ['정적스트레칭루틴프로그램', '요가및필라테스루틴프로그램'],
 ['등어깨뒤쪽스트레칭', '엉덩이스트레칭2', '넙다리앞쪽스트레칭', '양팔벌려전신비틀기', '골반스트레칭2', '회전근개스트레칭2'],
 ['무릎당겨올리기', '다리모아무릎누르기', '발목돌리기', '양발벌려무릎밀어내기'],
 ['전신루틴스트레칭', '하지루틴스트레칭2'],
 [],
 [],
 ['전신루틴스트레칭'],
 [],
 [],
 ['깍지끼고상체숙이기', '목스트레칭', '등어깨뒤쪽스트레칭', '아래팔스트레칭', '넙다리안쪽스트레칭', '허리스트레칭'],
 ['전신루틴스트레칭', '목스트레칭', '등어깨뒤쪽스트레칭', '넙다리뒤쪽스트레칭', '하지루틴스트레칭1'],


In [23]:
len(end)

7115

In [24]:
exercise_prepare = set()
for j in range(len(prepare)):
    for i in prepare[j]:
        exercise_prepare.add(i)
len(exercise_prepare)
exercise_prepare = list(exercise_prepare)
exercise_prepare = exercise_prepare[1:]
exercise_prepare

['누워서밀기',
 '누워서배가로근수축II',
 '뒤꿈치높이들어뛰기',
 '앉아윗몸앞으로굽히기',
 '허리감아볼돌리기',
 '1단줄넘기',
 '스텝퍼오르내리기',
 '스텝퍼올라가서점프하여착지하기',
 '옆으로팔대고버티기',
 '어깨올리기',
 '머리뒤로깍지끼고상체숙이기',
 '가슴어깨펴기',
 '스텝박스오르내리기',
 '엉덩이스트레칭',
 '나무자세',
 '마주보고종아리펴기',
 '앉아서몸통움츠리기',
 '옆으로팔벌리며점프하기',
 '누워서하늘자전거',
 '몸통들어올리기',
 '고정식자전거타기',
 '엎드려팔다리교차올리기',
 '네발걷기',
 '아쿠아로빅운동프로그램루틴',
 '발목돌리기',
 '밴드잡고몸통옆으로굽히기',
 '서서상체일으키기',
 '아령앞으로들어올리기',
 '서서어깨들어올리기',
 '조깅',
 '상체앞으로숙이기',
 '윗몸올리기',
 '의자에앉아다리뻗어올리기',
 '앉아서한발앞으로굽히기',
 '다리옆으로들어올리기',
 '엉덩이늘리기',
 '양팔벌려전신비틀기',
 '어깨스트레칭',
 '밴드걸고옆으로누워다리올리기',
 '시소우',
 '등대고대퇴이두근스트레칭',
 '대퇴이두근스트레칭2',
 '무릎대고옆으로기울이기',
 '합장하여앞으로숙이기',
 '짐볼이용해앉았다일어서기',
 '발가락폄근스트레칭',
 '앉아서다리굽히기',
 '무릎높여제자리달리기',
 '물통으로양팔들어올리기',
 '아기자세',
 '한쪽다리펴고상체숙이기',
 '배스트레칭',
 '밴드걸고엎드려서다리구부리기',
 '넙다리안쪽스트레칭',
 '고정식트레드밀에서걷기',
 '반달자세',
 '다리꼬아상체앞으로숙이기',
 '비복근스트레칭',
 '앉아서당겨내리기',
 '실내자전거타기',
 '앞으로나가며앉았다일어서기',
 '앉았다일어서기',
 '팔꿈치머리뒤로젖히기',
 '바벨들어올리기',
 '전갈자세',
 '의자잡고한발들기',
 '매달려서다리들기',
 '물병들고한발앞으로내밀고앉았다일어서기',
 '어깨누르기',
 '의자앉아다리로짐볼쥐기',
 '팔당기기',
 '서서한팔들어오른쪽왼쪽뻗기',
 '누워서다리들어올리기

In [25]:
exercise_main = set()
for j in range(len(main)):
    for i in main[j]:
        exercise_main.add(i)
len(exercise_main)
exercise_main = list(exercise_main)
exercise_main = exercise_main[1:]
exercise_main

['누워서밀기',
 '누워서배가로근수축II',
 '뒤꿈치높이들어뛰기',
 '앉아윗몸앞으로굽히기',
 '허리감아볼돌리기',
 '1단줄넘기',
 '스텝퍼오르내리기',
 '옆으로팔대고버티기',
 '스텝퍼올라가서점프하여착지하기',
 '수건이용하여장딴지늘리기',
 '어깨올리기',
 '탄력밴드전방으로당기기',
 '머리뒤로깍지끼고상체숙이기',
 '가슴어깨펴기',
 '머리위로공넘기기',
 '스텝박스오르내리기',
 'S자달리기',
 '엉덩이스트레칭',
 '나무자세',
 '좌우양발모아점프하기',
 '누워서하늘자전거',
 '앉아서몸통움츠리기',
 '옆으로팔벌리며점프하기',
 '몸통들어올리기',
 '고정식자전거타기',
 '엎드려팔다리교차올리기',
 '짐볼앉아뒤꿈치들기',
 '네발걷기',
 '아쿠아로빅운동프로그램루틴',
 '발목돌리기',
 '짐볼앉기',
 '밴드잡고몸통옆으로굽히기',
 '서서상체일으키기',
 '아령앞으로들어올리기',
 '무릎들어연속뛰기',
 '서서어깨들어올리기',
 '조깅',
 '상체앞으로숙이기',
 '앉아서양팔당기기',
 '윗몸올리기',
 '의자에앉아다리뻗어올리기',
 '짐볼전완대고버티기',
 '앉아서한발앞으로굽히기',
 '앉아서밴드당기기',
 '다리옆으로들어올리기',
 '몸기울이기회전하기',
 '엉덩이늘리기',
 '양팔벌려전신비틀기',
 '어깨스트레칭',
 '밴드걸고옆으로누워다리올리기',
 '시소우',
 '대퇴이두근스트레칭2',
 '등대고대퇴이두근스트레칭',
 '종아리사이감아돌리기',
 '짐볼에다리올리고엉덩이들어올리기',
 '무릎굽혀엉덩이들어올리기',
 '무릎대고옆으로기울이기',
 '합장하여앞으로숙이기',
 '짐볼이용해앉았다일어서기',
 '물누르기올리기',
 '사다리걷기',
 '발가락폄근스트레칭',
 '앉아서다리굽히기',
 '무릎높여제자리달리기',
 '물통으로양팔들어올리기',
 '아쿠아로빅-물누르기올리기',
 '밴드다리올려버티기',
 '바벨당겨올리기',
 '두발모아걷기',
 '아기자세',
 '한쪽다리펴고상체숙이기',
 '배스트레칭',
 '짐볼이용근력운동루틴프로그램

In [26]:
exercise_end = set()
for j in range(len(end)):
    for i in end[j]:
        exercise_end.add(i)
len(exercise_end)
exercise_end = list(exercise_end)
exercise_end = exercise_end[1:]
exercise_end

['줄넘기',
 '왜가리자세',
 '다리벌려옆으로상체숙이기',
 '사이드한발뛰기',
 '사다리좌우뛰기',
 '옆구리늘리기',
 '짐볼을이용한동적루틴스트레칭',
 '스타투니풀',
 '어깨뒤쪽스트레칭',
 '의자이용하기',
 '몸앞으로굽히기',
 '엎드려상체들어올리기',
 '앉아윗몸앞으로굽히기',
 '대퇴사두근스트레칭',
 '골반스트레칭2',
 '1단줄넘기',
 '스텝퍼오르내리기',
 '스텝퍼올라가서점프하여착지하기',
 '기',
 '레그스윙',
 '소머리자세',
 '무릎당겨올리기',
 '온몸뻗어주기',
 '앉은산자세',
 '가슴어깨펴기',
 '발닿기',
 '슴어깨앞쪽스트레칭',
 '무릎굽혀가슴닿기',
 '자가근막이완술루틴스트레칭',
 '스텝퍼뛰어서넘어가기',
 '양발나란히서기',
 '엉덩이스트레칭',
 '마주보고상체좌우비틀기',
 '한발뒤로빼고앞으로굽히기',
 '가슴어깨스트레칭',
 '다리벌려앞으로상체숙이기',
 '양발벌려무릎밀어내기',
 '서서발목뒤로당기기',
 '엉덩이스트레칭2',
 '트레드밀에서걷기',
 '누워발목당겨주기',
 '몸통들어올리기',
 '고정식자전거타기',
 '골반스트레칭',
 '좌식생활자를위한동적루틴스트레칭',
 '네발걷기',
 '모관운동',
 '발목돌리기',
 '다리모아상체숙이기',
 '유산소운동전동적루틴스트레칭',
 '등어깨뒤쪽스트레칭',
 '팔벌려뛰기',
 '물고기자세',
 '아래팔스트레칭',
 '한발앞굽이팔위로뻗어가슴내밀기',
 '버피운동',
 '전신틀어손벽마주치기',
 '조깅',
 '아령뒤로들어올리기',
 '깍지끼고상체숙이기',
 '상체앞으로숙이기',
 '옆으로누워버티기',
 '대퇴이두근스트레칭',
 '나란히서서손잡고끌어당기기',
 '뛰어내렸다가바로점프하기',
 '회전근개스트레칭2',
 '휴식자세',
 '앉아서한발앞으로굽히기',
 '척추스트레칭',
 '몸기울이기회전하기',
 '엉덩이늘리기',
 '목돌림스트레칭',
 '양팔벌려전신비틀기',
 '골다공증을위한스트레칭',
 '어깨스트레칭',
 '앉아서다리펴기',
 '래팔스트레칭',
 '시소우

In [27]:
p = [[0]*len(exercise_prepare) for i in range(len(result1))]
m = [[0]*len(exercise_main) for i in range(len(result1))]
e = [[0]*len(exercise_end) for i in range(len(result1))]

In [28]:
for j in range(len(exercise_prepare)):
    for i in range (len(result1)):
        if exercise_prepare[j] in prepare[i]:
            p[i][j]=1

In [29]:
for j in range(len(exercise_main)):
    for i in range (len(result1)):
        if exercise_main[j] in main[i]:
            m[i][j]=1

In [30]:
for j in range(len(exercise_end)):
    for i in range (len(result1)):
        if exercise_end[j] in end[i]:
            e[i][j]=1

In [31]:
p = pd.DataFrame(p)
m = pd.DataFrame(m)
e = pd.DataFrame(e)

In [32]:
p.columns = exercise_prepare
m.columns = exercise_main
e.columns = exercise_end

In [33]:
exercise_prepare

['누워서밀기',
 '누워서배가로근수축II',
 '뒤꿈치높이들어뛰기',
 '앉아윗몸앞으로굽히기',
 '허리감아볼돌리기',
 '1단줄넘기',
 '스텝퍼오르내리기',
 '스텝퍼올라가서점프하여착지하기',
 '옆으로팔대고버티기',
 '어깨올리기',
 '머리뒤로깍지끼고상체숙이기',
 '가슴어깨펴기',
 '스텝박스오르내리기',
 '엉덩이스트레칭',
 '나무자세',
 '마주보고종아리펴기',
 '앉아서몸통움츠리기',
 '옆으로팔벌리며점프하기',
 '누워서하늘자전거',
 '몸통들어올리기',
 '고정식자전거타기',
 '엎드려팔다리교차올리기',
 '네발걷기',
 '아쿠아로빅운동프로그램루틴',
 '발목돌리기',
 '밴드잡고몸통옆으로굽히기',
 '서서상체일으키기',
 '아령앞으로들어올리기',
 '서서어깨들어올리기',
 '조깅',
 '상체앞으로숙이기',
 '윗몸올리기',
 '의자에앉아다리뻗어올리기',
 '앉아서한발앞으로굽히기',
 '다리옆으로들어올리기',
 '엉덩이늘리기',
 '양팔벌려전신비틀기',
 '어깨스트레칭',
 '밴드걸고옆으로누워다리올리기',
 '시소우',
 '등대고대퇴이두근스트레칭',
 '대퇴이두근스트레칭2',
 '무릎대고옆으로기울이기',
 '합장하여앞으로숙이기',
 '짐볼이용해앉았다일어서기',
 '발가락폄근스트레칭',
 '앉아서다리굽히기',
 '무릎높여제자리달리기',
 '물통으로양팔들어올리기',
 '아기자세',
 '한쪽다리펴고상체숙이기',
 '배스트레칭',
 '밴드걸고엎드려서다리구부리기',
 '넙다리안쪽스트레칭',
 '고정식트레드밀에서걷기',
 '반달자세',
 '다리꼬아상체앞으로숙이기',
 '비복근스트레칭',
 '앉아서당겨내리기',
 '실내자전거타기',
 '앞으로나가며앉았다일어서기',
 '앉았다일어서기',
 '팔꿈치머리뒤로젖히기',
 '바벨들어올리기',
 '전갈자세',
 '의자잡고한발들기',
 '매달려서다리들기',
 '물병들고한발앞으로내밀고앉았다일어서기',
 '어깨누르기',
 '의자앉아다리로짐볼쥐기',
 '팔당기기',
 '서서한팔들어오른쪽왼쪽뻗기',
 '누워서다리들어올리기

In [34]:
drop_prepare = list()
for i in range(len(exercise_prepare)):
    if (len(p[exercise_prepare[i]][p[exercise_prepare[i]] == 1]) < 6):
        print(exercise_prepare[i],i)
        drop_prepare.append(exercise_prepare[i])

누워서밀기 0
허리감아볼돌리기 4
스텝퍼오르내리기 6
스텝퍼올라가서점프하여착지하기 7
옆으로팔대고버티기 8
어깨올리기 9
머리뒤로깍지끼고상체숙이기 10
스텝박스오르내리기 12
마주보고종아리펴기 15
앉아서몸통움츠리기 16
엎드려팔다리교차올리기 21
아쿠아로빅운동프로그램루틴 23
아령앞으로들어올리기 27
다리옆으로들어올리기 34
등대고대퇴이두근스트레칭 40
짐볼이용해앉았다일어서기 44
밴드걸고엎드려서다리구부리기 52
매달려서다리들기 66
의자앉아다리로짐볼쥐기 69
팔교대로올리기 75
팔로써클링누르기 77
앉았다일어나며점프하기 80
파워클린 81
탄력밴드이용평형성운동루틴프로그램 82
밴드잡고누워서다리밀기 83
양팔크게벌리기 84
앞차기하며뛰기 87
활자세 89
짐볼배에대고버티기 93
줄따라걷기 94
양발연속뛰기 97
양손번갈아공튀기기 98
50M달리기 103
누워서다리좌우로움직이기 104
옆구리늘리기 105
한발서서균형잡기 111
엎드려무릎당기기 112
누워서배가로근수축I 117
십(十)자달리기 126
덤벨잡고한발내밀어굽혔다펴기 128
사이드스텝 129
크런치사이클 130
고정한상태에서덤벨들고팔꿈치굽히기 132
옆으로걷기 136
누워서팔다리동시에들어올리기 138
사다리이용루틴운동 145
의자에앉아등굽혔다펴기 147
머신이용근력운동루틴프로그램 148
의자이용근력운동루틴프로그램 149
한발로점프하기 151
팔구부려등모으기 154
짐볼들고양옆으로돌리기 157
앉아서덤벨로손목굽히기 162
다리앞뒤로벌려굽혔다펴기 167
박스운동루틴프로그램 169
짐볼에서몸통돌리기 171
폼롤러앞으로굴리기 173
다리뻗어점프하기 181
덤벨잡고뒤꿈치들기 188
뛰어밀기 190
누워서공들고몸기울이기 194
사다리운동루틴프로그램 196
교차다리굽히기 198
다리교대로들어올리기 202
작은공을이용한동적루틴스트레칭 208
잔발치기 209
요통을위한스트레칭1 210
점프하며앞으로나가기 212
머리위로볼돌리기 216
허리비틀어볼주고받기 223
점프팔굽혀펴기 227
상체감아올리기 230
앉아서다리펴서들

In [35]:
drop_main = list()
for i in range(len(exercise_main)):
    if (len(m[exercise_main[i]][m[exercise_main[i]] == 1]) < 6):
        print(exercise_main[i],i)
        drop_main.append(exercise_main[i])

어깨올리기 10
탄력밴드전방으로당기기 11
가슴어깨펴기 13
S자달리기 16
짐볼앉아뒤꿈치들기 26
짐볼앉기 30
몸기울이기회전하기 45
무릎대고옆으로기울이기 56
물누르기올리기 59
밴드다리올려버티기 66
등척성운동-안쪽돌림 87
엉덩관절회전하기 98
요통을위한스트레칭2 114
활자세 123
50M달리기 140
짐볼앞으로밀기 141
발닿기 158
한발들어좌우돌리기 171
전신틀어손벽마주치기 182
회전근개스트레칭2 189
휴식자세 190
엎드려무릎연속차기 194
마주앉아대퇴이두근스트레칭2 201
어깨양옆으로돌리기 207
아쿠아로빅-발닿기 212
엎드려어깨늘리기 236
짐볼에엎드려서팔다리들기 241
계단두칸씩뛰기 243
뛰어밀기 246
관절염을위한심폐지구력운동 260
무릎당겨다리올리기 263
아쿠아로빅-옆구리늘리기 265
성화봉송 271
베개밟고위로양팔들기 274
베개밟고측면으로양팔들기 290
점프팔굽혀펴기 296
짐볼옆에두고어깨누르기 297
탄력밴드걸고서기 300
계단한발뛰기 302
짐볼양팔로밀기 304
목굽힘폄II 308
짐볼앉아몸통돌리기 319
유소년테스트 326
한발앞뒤교차뛰기 337
공위로던지고제자리돌아받기 338
협응력향상프로그램_계이름치기 360
아쿠아로빅-물당기기밀기 365
앞뒤지그재그뛰기 378
팔굽혀펴기(무릎대고실시) 384
훌라후프로공끌고가기 390
수동적관절가동범위운동 394
요통을위한근력운동 396
누워서뒤로팔굽혀펴기 404
종아리스트레칭 410
무릎대고상체뒤로젖히기 412
스타투니풀 422
대(大)자점프뛰기 424
레그스윙 430
자세낮춰이동하기 441
짐볼이용평형성루틴프로그램 444
아쿠아로빅-엉덩관절회전하기 455
짐볼앉아한발들기 461
스카프라인 478
등스트레칭 479
다리로짐볼들어올리기 484
의자잡고전방으로무릎굽혀들기 489
고혈압환자_심폐지구력운동 532
전진점프하며발바닥찍기 538
등척성운동-바깥돌림 548
자기체중이용평형성운동루틴프로그램 564
고혈압환자_순환식근력운동프로그램 565


In [36]:
drop_end = list()
for i in range(len(exercise_end)):
    if (len(e[exercise_end[i]][e[exercise_end[i]] == 1]) < 6):
        print(exercise_end[i],i)
        drop_end.append(exercise_end[i])

사이드한발뛰기 3
사다리좌우뛰기 4
옆구리늘리기 5
스타투니풀 7
의자이용하기 9
몸앞으로굽히기 10
1단줄넘기 15
스텝퍼오르내리기 16
스텝퍼올라가서점프하여착지하기 17
기 18
레그스윙 19
소머리자세 20
발닿기 25
슴어깨앞쪽스트레칭 26
양발나란히서기 30
마주보고상체좌우비틀기 32
서서발목뒤로당기기 37
몸통들어올리기 41
네발걷기 45
아령뒤로들어올리기 58
옆으로누워버티기 61
나란히서서손잡고끌어당기기 63
뛰어내렸다가바로점프하기 64
척추스트레칭 68
몸기울이기회전하기 69
골다공증을위한스트레칭 73
래팔스트레칭 76
시소우 77
대퇴이두근스트레칭2 81
발끝당기기 82
발바닥치기 85
짐볼에다리올리고엉덩이들어올리기 86
물누르기올리기 89
앉아서상체앞옆으로기울기 92
발가락폄근스트레칭 94
다리굽혀허리비틀기 97
등스트레칭 99
어깨양옆으로돌리기 100
적스트레칭루틴프로그램 101
엎드려한발원그리기 103
짐볼들고양옆으로돌리기 105
앉아서덤벨로손목굽히기 111
엎드려양팔및다리들어올리기 115
짐볼에다리올리고좌우로움직이기 116
손목펴기굽히기 117
계단두발뛰기 121
사다리안팎뛰기 122
옆으로누워가슴열기 124
제자리뛰기 128
폼롤러앞으로굴리기 130
의자잡고팔뒤로굽히기 137
다리굽혀(W자)상체뒤로눕기 138
결가부좌 142
줄넘기운동 150
치매를위한스트레칭(의자) 152
덤벨옆으로들어올리기 154
어깨누르기 155
의자이용유연성운동루틴프로그램 156
엉덩관절회전하기 159
의자에앉아볼돌리기 162
폼롤러밀며몸앞으로숙이기 164
다리뻗어상체숙이기 165
양팔벌려높이뛰기 166
겨드랑이늘리기 168
팔교대로올리기 169
의자에앉아가슴뒤로젖히기 171
앉았다일어서면서점프하기 175
전진점프하며발뒤꿈치찍기 180
사다리옆으로발옮기기 181
좌우로선넘기 183
전진점프하며발바닥찍기 184
무릎당겨다리올리기 188
전사자세 190
계단뛰어오르기 191
엎드려버티기 193
앞차기하며뛰기 195
앞뒤로선넘기 196
아쿠아로빅 198
앞굽이뛰기 

In [37]:
p = p.drop(drop_prepare,axis=1)
m = m.drop(drop_main,axis=1)
e = e.drop(drop_end,axis=1)

In [38]:
p

누워서배가로근수축II  뒤꿈치높이들어뛰기  앉아윗몸앞으로굽히기  1단줄넘기  가슴어깨펴기  엉덩이스트레칭  나무자세  \
0               0          0           0      0       0        0     0   
1               0          0           0      0       0        0     0   
2               0          0           0      0       0        0     0   
3               0          0           0      0       0        0     0   
4               0          0           0      0       0        0     0   
...           ...        ...         ...    ...     ...      ...   ...   
7110            0          0           0      0       0        0     0   
7111            0          0           0      0       0        0     0   
7112            0          0           0      0       0        0     0   
7113            0          0           0      0       0        0     0   
7114            0          0           0      0       0        0     0   

      옆으로팔벌리며점프하기  누워서하늘자전거  몸통들어올리기  ...  엎드려다리들어올리기  옆구리스트레칭  목돌리기  달리기  \
0               0         0        0  ...           0        0     0    0   
1               0         0        1  ...           0        0     0    0   
2               0         0        0  ...           0        0     0    0   
3               0         0        0  ...           0        0     0    0   
4               0         0        0  ...           0        0     0    0   
...           ...       ...      ...  ...         ...      ...   ...  ...   
7110            0         0        0  ...           0        0     0    1   
7111            0         0        0  ...           0        0     0    0   
7112            0         0        0  ...           0        0     0    0   
7113            0         0        0  ...           0        1     0    0   
7114            0         0        0  ...           0        0     0    0   

      팔꿈치맞닿아원그리기  누워서전신뻗기  라켓으로공치며앞으로가기  엎드려팔로걷기  가슴어깨앞쪽스트레칭  깍지끼고목들어올리기  
0              0        0             0        0           0           0  
1              0        0             0        0           0           0  
2              0        0             0        0           0           0  
3              0        0             0        0           0           0  
4              0        0             0        0           0           0  
...          ...      ...           ...      ...         ...         ...  
7110           0        0             0        0           0           0  
7111           0        0             0        0           0           0  
7112           0        0             0        0           0           0  
7113           0        0             0        0           0           0  
7114           0        0             0        0           0           0  

[7115 rows x 282 columns]

In [39]:
m

누워서밀기  누워서배가로근수축II  뒤꿈치높이들어뛰기  앉아윗몸앞으로굽히기  허리감아볼돌리기  1단줄넘기  스텝퍼오르내리기  \
0         0            0          1           0         1      0         0   
1         0            0          0           0         0      0         0   
2         0            0          0           0         0      0         0   
3         0            0          0           0         0      0         0   
4         0            0          0           0         0      0         0   
...     ...          ...        ...         ...       ...    ...       ...   
7110      0            0          0           0         0      0         0   
7111      0            0          0           0         0      0         0   
7112      0            0          0           0         0      0         0   
7113      0            0          0           0         1      0         0   
7114      0            0          0           0         0      0         0   

      옆으로팔대고버티기  스텝퍼올라가서점프하여착지하기  수건이용하여장딴지늘리기  ...  연속상향점프하기  목돌리기  \
0             0                0             0  ...         0     0   
1             0                0             0  ...         0     0   
2             0                0             0  ...         0     0   
3             0                0             0  ...         0     0   
4             0                0             0  ...         0     0   
...         ...              ...           ...  ...       ...   ...   
7110          0                0             0  ...         0     0   
7111          0                0             0  ...         0     0   
7112          0                0             0  ...         0     0   
7113          0                0             0  ...         0     0   
7114          0                0             0  ...         0     0   

      앉아서엉덩이들고이동하기  달리기  팔꿈치맞닿아원그리기  누워서전신뻗기  엎드려팔로걷기  라켓으로공치며앞으로가기  \
0                0    0           0        0        0             0   
1                0    0           0        0        0             0   
2                0    0           0        0        0             0   
3                0    0           0        0        0             0   
4                0    0           0        0        0             0   
...            ...  ...         ...      ...      ...           ...   
7110             0    0           0        0        0             0   
7111             0    0           0        0        0             0   
7112             0    1           0        0        0             0   
7113             0    0           0        0        0             0   
7114             0    0           0        0        0             0   

      가슴어깨앞쪽스트레칭  깍지끼고목들어올리기  
0              0           0  
1              0           0  
2              0           0  
3              0           0  
4              0           0  
...          ...         ...  
7110           0           0  
7111           0           0  
7112           0           0  
7113           0           0  
7114           0           0  

[7115 rows x 500 columns]

In [40]:
e

줄넘기  왜가리자세  다리벌려옆으로상체숙이기  짐볼을이용한동적루틴스트레칭  어깨뒤쪽스트레칭  엎드려상체들어올리기  \
0       0      0             0               0         0           0   
1       0      0             0               0         0           0   
2       0      0             0               0         0           0   
3       0      0             0               0         0           0   
4       0      0             0               0         0           0   
...   ...    ...           ...             ...       ...         ...   
7110    0      0             0               0         0           0   
7111    0      0             0               0         0           0   
7112    0      0             0               0         0           0   
7113    0      0             0               0         0           0   
7114    0      0             0               0         0           0   

      앉아윗몸앞으로굽히기  대퇴사두근스트레칭  골반스트레칭2  무릎당겨올리기  ...  무릎대고상체뒤로젖히기  다리모아뒤로눕기  \
0              0          0        0        0  ...            0         0   
1              0          0        0        0  ...            0         0   
2              0          0        0        0  ...            0         0   
3              0          0        0        0  ...            0         0   
4              0          0        0        0  ...            0         0   
...          ...        ...      ...      ...  ...          ...       ...   
7110           0          0        0        0  ...            0         0   
7111           0          0        0        0  ...            0         0   
7112           0          0        0        0  ...            0         0   
7113           0          0        0        1  ...            0         0   
7114           0          0        0        0  ...            0         0   

      계단올라갔다내려오기  고양이자세  연속사이드스쿼드  누워서전신뻗기  회전근개스트레칭  가슴어깨앞쪽스트레칭  발목얹고다리잡아당기기  \
0              0      0         0        0         0           0            0   
1              0      0         0        0         0           0            0   
2              0      0         0        0         0           0            0   
3              0      0         0        0         0           0            0   
4              0      0         0        0         0           0            0   
...          ...    ...       ...      ...       ...         ...          ...   
7110           0      0         0        0         0           0            0   
7111           0      0         0        0         0           0            0   
7112           0      0         0        0         0           1            0   
7113           0      0         0        0         0           0            0   
7114           0      0         0        0         0           0            0   

      깍지끼고목들어올리기  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
7110           0  
7111           0  
7112           0  
7113           0  
7114           0  

[7115 rows x 139 columns]

### 준비운동

In [41]:
train = result1[['BMI','Weight','age','bending_forward','body_fat','diastolic_bp','grip_power','height','measure_time','sex','sit_up','step_inspection','step_recover_time','systolic_bp']]
label = p

In [42]:
from sklearn.preprocessing import StandardScaler  
from sklearn.model_selection import train_test_split 
from imblearn.over_sampling import SMOTE
#from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score, precision_score, recall_score, matthews_corrcoef, plot_roc_curve, confusion_matrix

P = list()
good_performance = list()
for i in range(len(p.columns)):
    #smote = SMOTE(random_state=0)
    #train_over,label_over = smote.fit_sample(train,label[p.columns[i]])
    #print('SMOTE 적용 전 학습용 피처/레이블 데이터 세트: ', train.shape, label[p.columns[i]].shape)
    #print('SMOTE 적용 후 학습용 피처/레이블 데이터 세트: ', train_over.shape, label_over.shape)
    #print('SMOTE 적용 후 레이블 값 분포: \n', label_over.value_counts())
    #train_features, test_features, train_labels, test_labels = train_test_split(train_over, label_over, stratify=label_over)
    #print(len(train_features), len(test_features))
    train_features, test_features, train_labels, test_labels = train_test_split(train, label[p.columns[i]], stratify=label[p.columns[i]])
    scaler = StandardScaler()  
    train_features = scaler.fit_transform(train_features)  
    test_features = scaler.transform(test_features)
    
    model = XGBClassifier(random_state=222)
    model.fit(train_features, train_labels)
    #model = LogisticRegression()
    #model.fit(train_features, train_labels)
    y_pred = model.predict(test_features)
    
    f1 = f1_score(test_labels, y_pred)
    mcc_score = matthews_corrcoef(test_labels, y_pred)
    precision = precision_score(test_labels, y_pred)
    recall = recall_score(test_labels, y_pred)        
    auc_score = roc_auc_score(test_labels, y_pred)
    acc_score = accuracy_score(test_labels, y_pred)
    print(i)
    print(confusion_matrix(test_labels, y_pred))
    tn, fp, fn, tp = confusion_matrix(test_labels, y_pred).ravel()
    print('tp, tn, fp, fn: ', (tp, tn, fp, fn))
    print("train_score: ",model.score(train_features, train_labels))
    print("test_score: ",model.score(test_features, test_labels))
    if model.score(test_features, test_labels) > 0.98:
        good_performance.append(i)
    P.append(model)

0
[[1777    0]
 [   0    2]]
tp, tn, fp, fn:  (2, 1777, 0, 0)
train_score:  1.0
test_score:  1.0
1
[[1777    0]
 [   1    1]]
tp, tn, fp, fn:  (1, 1777, 0, 1)
train_score:  0.9998125937031485
test_score:  0.9994378864530635
2
[[1777    0]
 [   2    0]]
tp, tn, fp, fn:  (0, 1777, 0, 2)
train_score:  0.9996251874062968
test_score:  0.9988757729061271
3
[[1773    0]
 [   2    4]]
tp, tn, fp, fn:  (4, 1773, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
4
[[1776    0]
 [   2    1]]
tp, tn, fp, fn:  (1, 1776, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
5
[[1690    2]
 [  40   47]]
tp, tn, fp, fn:  (47, 1690, 2, 40)
train_score:  1.0
test_score:  0.9763912310286678
6
[[1775    0]
 [   1    3]]
tp, tn, fp, fn:  (3, 1775, 0, 1)
train_score:  1.0
test_score:  0.9994378864530635
7
[[1775    0]
 [   0    4]]
tp, tn, fp, fn:  (4, 1775, 0, 0)
train_score:  1.0
test_score:  1.0
8
[[1774    0]
 [   1    4]]
tp, tn, fp, fn:  (4, 1774, 0, 1)
train_score:  1.0
test_score:  0.9994378

74
[[1776    0]
 [   0    3]]
tp, tn, fp, fn:  (3, 1776, 0, 0)
train_score:  1.0
test_score:  1.0
75
[[1776    0]
 [   2    1]]
tp, tn, fp, fn:  (1, 1776, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
76
[[1773    0]
 [   2    4]]
tp, tn, fp, fn:  (4, 1773, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
77
[[1774    0]
 [   2    3]]
tp, tn, fp, fn:  (3, 1774, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
78
[[1772    0]
 [   2    5]]
tp, tn, fp, fn:  (5, 1772, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
79
[[1771    0]
 [   2    6]]
tp, tn, fp, fn:  (6, 1771, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
80
[[1753    0]
 [  10   16]]
tp, tn, fp, fn:  (16, 1753, 0, 10)
train_score:  1.0
test_score:  0.9943788645306352
81
[[1775    0]
 [   1    3]]
tp, tn, fp, fn:  (3, 1775, 0, 1)
train_score:  1.0
test_score:  0.9994378864530635
82
[[1776    0]
 [   0    3]]
tp, tn, fp, fn:  (3, 1776, 0, 0)
train_score:  1.0
test_score:  1.0
83
[[1770  

148
[[1772    0]
 [   2    5]]
tp, tn, fp, fn:  (5, 1772, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
149
[[1770    0]
 [   2    7]]
tp, tn, fp, fn:  (7, 1770, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
150
[[1730    0]
 [  19   30]]
tp, tn, fp, fn:  (30, 1730, 0, 19)
train_score:  1.0
test_score:  0.9893198426082068
151
[[1766    0]
 [   4    9]]
tp, tn, fp, fn:  (9, 1766, 0, 4)
train_score:  1.0
test_score:  0.9977515458122541
152
[[1741    0]
 [  17   21]]
tp, tn, fp, fn:  (21, 1741, 0, 17)
train_score:  1.0
test_score:  0.9904440697020798
153
[[1752    0]
 [  13   14]]
tp, tn, fp, fn:  (14, 1752, 0, 13)
train_score:  1.0
test_score:  0.9926925238898258
154
[[1774    0]
 [   3    2]]
tp, tn, fp, fn:  (2, 1774, 0, 3)
train_score:  1.0
test_score:  0.9983136593591906
155
[[1773    0]
 [   3    3]]
tp, tn, fp, fn:  (3, 1773, 0, 3)
train_score:  1.0
test_score:  0.9983136593591906
156
[[1777    0]
 [   0    2]]
tp, tn, fp, fn:  (2, 1777, 0, 0)
train_score:  1.0


221
[[1763    0]
 [   4   12]]
tp, tn, fp, fn:  (12, 1763, 0, 4)
train_score:  1.0
test_score:  0.9977515458122541
222
[[1777    0]
 [   0    2]]
tp, tn, fp, fn:  (2, 1777, 0, 0)
train_score:  1.0
test_score:  1.0
223
[[1771    0]
 [   3    5]]
tp, tn, fp, fn:  (5, 1771, 0, 3)
train_score:  1.0
test_score:  0.9983136593591906
224
[[1739    0]
 [  19   21]]
tp, tn, fp, fn:  (21, 1739, 0, 19)
train_score:  1.0
test_score:  0.9893198426082068
225
[[1769    0]
 [   7    3]]
tp, tn, fp, fn:  (3, 1769, 0, 7)
train_score:  1.0
test_score:  0.9960652051714446
226
[[1747    0]
 [  13   19]]
tp, tn, fp, fn:  (19, 1747, 0, 13)
train_score:  1.0
test_score:  0.9926925238898258
227
[[1758    0]
 [   9   12]]
tp, tn, fp, fn:  (12, 1758, 0, 9)
train_score:  1.0
test_score:  0.9949409780775716
228
[[1769    0]
 [   5    5]]
tp, tn, fp, fn:  (5, 1769, 0, 5)
train_score:  1.0
test_score:  0.9971894322653176
229
[[1777    0]
 [   2    0]]
tp, tn, fp, fn:  (0, 1777, 0, 2)
train_score:  0.9996251874062968


In [43]:
print(len(m))
print(len(good_performance))

7115
270


In [44]:
for i in range(len(p.columns)):
    if p.iloc[1][i] == 1:
        print(i,p.columns[i])

9 몸통들어올리기
16 조깅
44 앉았다일어서기
64 걷기
77 윗몸일으키기
112 버피테스트
133 팔굽혀펴기
173 팔다리교차버티기
202 동적스트레칭루틴프로그램
234 정적스트레칭루틴프로그램
261 자전거타기


In [45]:
Jack = np.array([19.3,43.2,49.0,-10.0,36.0,88.0,11.1,149.8,2019.0,1.0,6.0,47.400,89.00,133.0])
Rose = np.array([18.5,48.7,47.0,-3.0,21.5,100.0,6.0,162.4,2019.0,1.0,13.0,47.400,91.00,139.0])
ME = np.array([22.5,66.3,26.0,-0.2,20.4,77.0,22.4,171.6,2019.0,1.0,15.0,46.2,112.0,122.0])
ME2 = np.array([20.5,64.3,40.0,-1.0,35.4,100.0,5.4,170.4,2019.0,1.0,12.0,43.6,119.0,130.0])
human = np.array([Jack, Rose, ME,ME2])

In [46]:
#.reshape(1,-1)
human = scaler.transform(human)

In [47]:
human

array([[-1.038, -1.177,  1.871, -0.546,  0.386,  0.698, -0.685, -0.889,
        -0.929,  0.721, -0.847,  0.823, -0.798,  0.66 ],
       [-1.171, -0.908,  1.692,  0.013, -1.043,  1.654, -1.287,  0.097,
        -0.929,  0.721, -0.115,  0.823, -0.684,  1.047],
       [-0.504, -0.044, -0.194,  0.237, -1.151, -0.178,  0.647,  0.817,
        -0.929,  0.721,  0.095,  0.637,  0.509, -0.049],
       [-0.837, -0.142,  1.063,  0.173,  0.326,  1.654, -1.358,  0.723,
        -0.929,  0.721, -0.219,  0.235,  0.907,  0.467]])

In [48]:
for i in range(len(P)):
    if (P[i].predict(human[1].reshape(1, -1))==1):
        print(p.columns[i]+" 운동이 필요합니다")

몸통들어올리기 운동이 필요합니다
조깅 운동이 필요합니다
앉았다일어서기 운동이 필요합니다
걷기 운동이 필요합니다
팔굽혀펴기 운동이 필요합니다
팔다리교차버티기 운동이 필요합니다
동적스트레칭루틴프로그램 운동이 필요합니다
정적스트레칭루틴프로그램 운동이 필요합니다
자전거타기 운동이 필요합니다


### 본운동

In [49]:
train = result1[['BMI','Weight','age','bending_forward','body_fat','diastolic_bp','grip_power','height','measure_time','sex','sit_up','step_inspection','step_recover_time','systolic_bp']]
label = m

In [50]:
from sklearn.preprocessing import StandardScaler  
from sklearn.model_selection import train_test_split 
from imblearn.over_sampling import SMOTE
#from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score, precision_score, recall_score, matthews_corrcoef, plot_roc_curve, confusion_matrix

M = list()
good_performance = list()
for i in range(len(m.columns)):
    #smote = SMOTE(random_state=0)
    #train_over,label_over = smote.fit_sample(train,label[p.columns[i]])
    #print('SMOTE 적용 전 학습용 피처/레이블 데이터 세트: ', train.shape, label[p.columns[i]].shape)
    #print('SMOTE 적용 후 학습용 피처/레이블 데이터 세트: ', train_over.shape, label_over.shape)
    #print('SMOTE 적용 후 레이블 값 분포: \n', label_over.value_counts())
    #train_features, test_features, train_labels, test_labels = train_test_split(train_over, label_over, stratify=label_over)
    #print(len(train_features), len(test_features))
    train_features, test_features, train_labels, test_labels = train_test_split(train, label[m.columns[i]], stratify=label[m.columns[i]])
    scaler = StandardScaler()  
    train_features = scaler.fit_transform(train_features)  
    test_features = scaler.transform(test_features)
    
    model = XGBClassifier(random_state=222)
    model.fit(train_features, train_labels)
    #model = LogisticRegression()
    #model.fit(train_features, train_labels)
    y_pred = model.predict(test_features)
    
    f1 = f1_score(test_labels, y_pred)
    mcc_score = matthews_corrcoef(test_labels, y_pred)
    precision = precision_score(test_labels, y_pred)
    recall = recall_score(test_labels, y_pred)        
    auc_score = roc_auc_score(test_labels, y_pred)
    acc_score = accuracy_score(test_labels, y_pred)
    print(i)
    print(confusion_matrix(test_labels, y_pred))
    tn, fp, fn, tp = confusion_matrix(test_labels, y_pred).ravel()
    print('tp, tn, fp, fn: ', (tp, tn, fp, fn))
    print("train_score: ",model.score(train_features, train_labels))
    print("test_score: ",model.score(test_features, test_labels))
    if model.score(test_features, test_labels) > 0.98:
        good_performance.append(i)
    M.append(model)

0
[[1775    0]
 [   3    1]]
tp, tn, fp, fn:  (1, 1775, 0, 3)
train_score:  1.0
test_score:  0.9983136593591906
1
[[1773    0]
 [   3    3]]
tp, tn, fp, fn:  (3, 1773, 0, 3)
train_score:  1.0
test_score:  0.9983136593591906
2
[[1768    0]
 [   4    7]]
tp, tn, fp, fn:  (7, 1768, 0, 4)
train_score:  1.0
test_score:  0.9977515458122541
3
[[1775    0]
 [   0    4]]
tp, tn, fp, fn:  (4, 1775, 0, 0)
train_score:  1.0
test_score:  1.0
4
[[1773    0]
 [   0    6]]
tp, tn, fp, fn:  (6, 1773, 0, 0)
train_score:  1.0
test_score:  1.0
5
[[1729    1]
 [  16   33]]
tp, tn, fp, fn:  (33, 1729, 1, 16)
train_score:  1.0
test_score:  0.9904440697020798
6
[[1762    2]
 [   6    9]]
tp, tn, fp, fn:  (9, 1762, 2, 6)
train_score:  1.0
test_score:  0.9955030916245081
7
[[1765    2]
 [   6    6]]
tp, tn, fp, fn:  (6, 1765, 2, 6)
train_score:  1.0
test_score:  0.9955030916245081
8
[[1775    0]
 [   2    2]]
tp, tn, fp, fn:  (2, 1775, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
9
[[1776    0]
 [   

73
[[1657    0]
 [  46   76]]
tp, tn, fp, fn:  (76, 1657, 0, 46)
train_score:  0.9998125937031485
test_score:  0.9741427768409219
74
[[1774    0]
 [   3    2]]
tp, tn, fp, fn:  (2, 1774, 0, 3)
train_score:  1.0
test_score:  0.9983136593591906
75
[[1382   28]
 [ 160  209]]
tp, tn, fp, fn:  (209, 1382, 28, 160)
train_score:  0.9926911544227887
test_score:  0.8943226531759415
76
[[1777    0]
 [   2    0]]
tp, tn, fp, fn:  (0, 1777, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
77
[[1764    0]
 [   9    6]]
tp, tn, fp, fn:  (6, 1764, 0, 9)
train_score:  1.0
test_score:  0.9949409780775716
78
[[1777    0]
 [   2    0]]
tp, tn, fp, fn:  (0, 1777, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
79
[[1777    0]
 [   1    1]]
tp, tn, fp, fn:  (1, 1777, 0, 1)
train_score:  1.0
test_score:  0.9994378864530635
80
[[1771    0]
 [   3    5]]
tp, tn, fp, fn:  (5, 1771, 0, 3)
train_score:  1.0
test_score:  0.9983136593591906
81
[[1761    2]
 [   4   12]]
tp, tn, fp, fn:  (12, 1761, 2

145
[[1771    0]
 [   3    5]]
tp, tn, fp, fn:  (5, 1771, 0, 3)
train_score:  1.0
test_score:  0.9983136593591906
146
[[1670    2]
 [  41   66]]
tp, tn, fp, fn:  (66, 1670, 2, 41)
train_score:  0.9998125937031485
test_score:  0.9758291174817313
147
[[1777    0]
 [   1    1]]
tp, tn, fp, fn:  (1, 1777, 0, 1)
train_score:  1.0
test_score:  0.9994378864530635
148
[[1773    0]
 [   3    3]]
tp, tn, fp, fn:  (3, 1773, 0, 3)
train_score:  1.0
test_score:  0.9983136593591906
149
[[1742    0]
 [  12   25]]
tp, tn, fp, fn:  (25, 1742, 0, 12)
train_score:  1.0
test_score:  0.9932546374367622
150
[[1745    3]
 [  11   20]]
tp, tn, fp, fn:  (20, 1745, 3, 11)
train_score:  1.0
test_score:  0.9921304103428893
151
[[1776    0]
 [   2    1]]
tp, tn, fp, fn:  (1, 1776, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
152
[[1777    0]
 [   0    2]]
tp, tn, fp, fn:  (2, 1777, 0, 0)
train_score:  1.0
test_score:  1.0
153
[[1776    0]
 [   2    1]]
tp, tn, fp, fn:  (1, 1776, 0, 2)
train_score:  1.0


218
[[1777    0]
 [   1    1]]
tp, tn, fp, fn:  (1, 1777, 0, 1)
train_score:  1.0
test_score:  0.9994378864530635
219
[[1733    0]
 [  16   30]]
tp, tn, fp, fn:  (30, 1733, 0, 16)
train_score:  0.9998125937031485
test_score:  0.9910061832490163
220
[[1767    0]
 [   4    8]]
tp, tn, fp, fn:  (8, 1767, 0, 4)
train_score:  1.0
test_score:  0.9977515458122541
221
[[1464   15]
 [ 138  162]]
tp, tn, fp, fn:  (162, 1464, 15, 138)
train_score:  0.9921289355322339
test_score:  0.9139966273187183
222
[[1767    0]
 [   4    8]]
tp, tn, fp, fn:  (8, 1767, 0, 4)
train_score:  1.0
test_score:  0.9977515458122541
223
[[1774    0]
 [   0    5]]
tp, tn, fp, fn:  (5, 1774, 0, 0)
train_score:  1.0
test_score:  1.0
224
[[1732    1]
 [  21   25]]
tp, tn, fp, fn:  (25, 1732, 1, 21)
train_score:  1.0
test_score:  0.9876335019673974
225
[[1775    0]
 [   0    4]]
tp, tn, fp, fn:  (4, 1775, 0, 0)
train_score:  1.0
test_score:  1.0
226
[[1772    1]
 [   4    2]]
tp, tn, fp, fn:  (2, 1772, 1, 4)
train_score:  1

290
[[1770    0]
 [   6    3]]
tp, tn, fp, fn:  (3, 1770, 0, 6)
train_score:  0.9998125937031485
test_score:  0.9966273187183811
291
[[1775    0]
 [   1    3]]
tp, tn, fp, fn:  (3, 1775, 0, 1)
train_score:  1.0
test_score:  0.9994378864530635
292
[[1777    0]
 [   2    0]]
tp, tn, fp, fn:  (0, 1777, 0, 2)
train_score:  0.9996251874062968
test_score:  0.9988757729061271
293
[[1725    0]
 [  28   26]]
tp, tn, fp, fn:  (26, 1725, 0, 28)
train_score:  1.0
test_score:  0.9842608206857786
294
[[1769    0]
 [   5    5]]
tp, tn, fp, fn:  (5, 1769, 0, 5)
train_score:  1.0
test_score:  0.9971894322653176
295
[[1775    0]
 [   3    1]]
tp, tn, fp, fn:  (1, 1775, 0, 3)
train_score:  1.0
test_score:  0.9983136593591906
296
[[1723    0]
 [  22   34]]
tp, tn, fp, fn:  (34, 1723, 0, 22)
train_score:  1.0
test_score:  0.9876335019673974
297
[[1776    0]
 [   0    3]]
tp, tn, fp, fn:  (3, 1776, 0, 0)
train_score:  1.0
test_score:  1.0
298
[[1772    0]
 [   4    3]]
tp, tn, fp, fn:  (3, 1772, 0, 4)
train

test_score:  0.9966273187183811
362
[[1757    0]
 [  10   12]]
tp, tn, fp, fn:  (12, 1757, 0, 10)
train_score:  1.0
test_score:  0.9943788645306352
363
[[1771    0]
 [   2    6]]
tp, tn, fp, fn:  (6, 1771, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
364
[[1777    0]
 [   1    1]]
tp, tn, fp, fn:  (1, 1777, 0, 1)
train_score:  0.9998125937031485
test_score:  0.9994378864530635
365
[[1756    0]
 [  11   12]]
tp, tn, fp, fn:  (12, 1756, 0, 11)
train_score:  1.0
test_score:  0.9938167509836987
366
[[1776    0]
 [   1    2]]
tp, tn, fp, fn:  (2, 1776, 0, 1)
train_score:  1.0
test_score:  0.9994378864530635
367
[[1774    0]
 [   0    5]]
tp, tn, fp, fn:  (5, 1774, 0, 0)
train_score:  1.0
test_score:  1.0
368
[[1761    0]
 [   4   14]]
tp, tn, fp, fn:  (14, 1761, 0, 4)
train_score:  1.0
test_score:  0.9977515458122541
369
[[1768    0]
 [   5    6]]
tp, tn, fp, fn:  (6, 1768, 0, 5)
train_score:  1.0
test_score:  0.9971894322653176
370
[[1772    0]
 [   2    5]]
tp, tn, fp, fn:  (5,

434
[[1772    0]
 [   0    7]]
tp, tn, fp, fn:  (7, 1772, 0, 0)
train_score:  1.0
test_score:  1.0
435
[[1763    0]
 [   5   11]]
tp, tn, fp, fn:  (11, 1763, 0, 5)
train_score:  1.0
test_score:  0.9971894322653176
436
[[1775    0]
 [   0    4]]
tp, tn, fp, fn:  (4, 1775, 0, 0)
train_score:  1.0
test_score:  1.0
437
[[1759    0]
 [   9   11]]
tp, tn, fp, fn:  (11, 1759, 0, 9)
train_score:  1.0
test_score:  0.9949409780775716
438
[[1585    7]
 [  74  113]]
tp, tn, fp, fn:  (113, 1585, 7, 74)
train_score:  0.9998125937031485
test_score:  0.954468802698145
439
[[1716    0]
 [  27   36]]
tp, tn, fp, fn:  (36, 1716, 0, 27)
train_score:  1.0
test_score:  0.984822934232715
440
[[1769    0]
 [   4    6]]
tp, tn, fp, fn:  (6, 1769, 0, 4)
train_score:  1.0
test_score:  0.9977515458122541
441
[[1776    0]
 [   1    2]]
tp, tn, fp, fn:  (2, 1776, 0, 1)
train_score:  1.0
test_score:  0.9994378864530635
442
[[1643    2]
 [  42   92]]
tp, tn, fp, fn:  (92, 1643, 2, 42)
train_score:  0.9998125937031485

In [51]:
print(len(m))
print(len(good_performance))

7115
475


In [52]:
for i in range(len(m.columns)):
    if m.iloc[1][i] == 1:
        print(i,m.columns[i])

In [53]:
Jack = np.array([19.3,43.2,49.0,-10.0,36.0,88.0,11.1,149.8,2019.0,1.0,6.0,47.400,89.00,133.0])
Rose = np.array([18.5,48.7,47.0,-3.0,21.5,100.0,6.0,162.4,2019.0,1.0,13.0,47.400,91.00,139.0])
ME = np.array([22.5,66.3,26.0,-0.2,20.4,77.0,22.4,171.6,2019.0,1.0,15.0,46.2,112.0,122.0])
ME2 = np.array([20.5,64.3,40.0,-1.0,35.4,100.0,5.4,170.4,2019.0,1.0,12.0,43.6,119.0,130.0])
human = np.array([Jack, Rose, ME,ME2])

In [54]:
#.reshape(1,-1)
human = scaler.transform(human)

In [55]:
human

array([[-1.029, -1.158,  1.904, -0.539,  0.38 ,  0.691, -0.676, -0.877,
        -0.932,  0.729, -0.846,  0.827, -0.802,  0.668],
       [-1.163, -0.892,  1.724,  0.023, -1.048,  1.64 , -1.28 ,  0.098,
        -0.932,  0.729, -0.106,  0.827, -0.688,  1.054],
       [-0.495, -0.039, -0.174,  0.248, -1.157, -0.179,  0.662,  0.81 ,
        -0.932,  0.729,  0.105,  0.639,  0.506, -0.04 ],
       [-0.829, -0.136,  1.091,  0.184,  0.321,  1.64 , -1.351,  0.717,
        -0.932,  0.729, -0.212,  0.233,  0.904,  0.475]])

In [56]:
for i in range(len(M)):
    if (M[i].predict(human[3].reshape(1, -1))==1):
        print(m.columns[i]+" 운동이 필요합니다")

### END

In [57]:
train = result1[['BMI','Weight','age','bending_forward','body_fat','diastolic_bp','grip_power','height','measure_time','sex','sit_up','step_inspection','step_recover_time','systolic_bp']]
label = e

In [58]:
from sklearn.preprocessing import StandardScaler  
from sklearn.model_selection import train_test_split 
from imblearn.over_sampling import SMOTE
#from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score, precision_score, recall_score, matthews_corrcoef, plot_roc_curve, confusion_matrix

E = list()
good_performance = list()
for i in range(len(e.columns)):
    #smote = SMOTE(random_state=0)
    #train_over,label_over = smote.fit_sample(train,label[p.columns[i]])
    #print('SMOTE 적용 전 학습용 피처/레이블 데이터 세트: ', train.shape, label[p.columns[i]].shape)
    #print('SMOTE 적용 후 학습용 피처/레이블 데이터 세트: ', train_over.shape, label_over.shape)
    #print('SMOTE 적용 후 레이블 값 분포: \n', label_over.value_counts())
    #train_features, test_features, train_labels, test_labels = train_test_split(train_over, label_over, stratify=label_over)
    #print(len(train_features), len(test_features))
    train_features, test_features, train_labels, test_labels = train_test_split(train, label[e.columns[i]], stratify=label[e.columns[i]])
    scaler = StandardScaler()  
    train_features = scaler.fit_transform(train_features)  
    test_features = scaler.transform(test_features)
    
    model = XGBClassifier(random_state=222)
    model.fit(train_features, train_labels)
    #model = LogisticRegression()
    #model.fit(train_features, train_labels)
    y_pred = model.predict(test_features)
    
    f1 = f1_score(test_labels, y_pred)
    mcc_score = matthews_corrcoef(test_labels, y_pred)
    precision = precision_score(test_labels, y_pred)
    recall = recall_score(test_labels, y_pred)        
    auc_score = roc_auc_score(test_labels, y_pred)
    acc_score = accuracy_score(test_labels, y_pred)
    print(i)
    print(confusion_matrix(test_labels, y_pred))
    tn, fp, fn, tp = confusion_matrix(test_labels, y_pred).ravel()
    print('tp, tn, fp, fn: ', (tp, tn, fp, fn))
    print("train_score: ",model.score(train_features, train_labels))
    print("test_score: ",model.score(test_features, test_labels))
    if model.score(test_features, test_labels) > 0.98:
        good_performance.append(i)
    E.append(model)

0
[[1776    0]
 [   1    2]]
tp, tn, fp, fn:  (2, 1776, 0, 1)
train_score:  1.0
test_score:  0.9994378864530635
1
[[1776    0]
 [   2    1]]
tp, tn, fp, fn:  (1, 1776, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
2
[[1758    0]
 [   5   16]]
tp, tn, fp, fn:  (16, 1758, 0, 5)
train_score:  1.0
test_score:  0.9971894322653176
3
[[1772    0]
 [   2    5]]
tp, tn, fp, fn:  (5, 1772, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
4
[[1773    0]
 [   0    6]]
tp, tn, fp, fn:  (6, 1773, 0, 0)
train_score:  1.0
test_score:  1.0
5
[[1758    0]
 [   9   12]]
tp, tn, fp, fn:  (12, 1758, 0, 9)
train_score:  1.0
test_score:  0.9949409780775716
6
[[1753    1]
 [  12   13]]
tp, tn, fp, fn:  (13, 1753, 1, 12)
train_score:  1.0
test_score:  0.9926925238898258
7
[[1771    2]
 [   2    4]]
tp, tn, fp, fn:  (4, 1771, 2, 2)
train_score:  1.0
test_score:  0.9977515458122541
8
[[1774    0]
 [   2    3]]
tp, tn, fp, fn:  (3, 1774, 0, 2)
train_score:  1.0
test_score:  0.9988757729061271
9
[

73
[[1717    1]
 [  26   35]]
tp, tn, fp, fn:  (35, 1717, 1, 26)
train_score:  1.0
test_score:  0.984822934232715
74
[[1764    0]
 [   4   11]]
tp, tn, fp, fn:  (11, 1764, 0, 4)
train_score:  1.0
test_score:  0.9977515458122541
75
[[1705    1]
 [  33   40]]
tp, tn, fp, fn:  (40, 1705, 1, 33)
train_score:  0.9998125937031485
test_score:  0.9808881394041596
76
[[1777    0]
 [   0    2]]
tp, tn, fp, fn:  (2, 1777, 0, 0)
train_score:  0.9996251874062968
test_score:  1.0
77
[[1701    1]
 [  30   47]]
tp, tn, fp, fn:  (47, 1701, 1, 30)
train_score:  1.0
test_score:  0.9825744800449691
78
[[1703    0]
 [  38   38]]
tp, tn, fp, fn:  (38, 1703, 0, 38)
train_score:  1.0
test_score:  0.9786396852164138
79
[[1777    0]
 [   0    2]]
tp, tn, fp, fn:  (2, 1777, 0, 0)
train_score:  0.9996251874062968
test_score:  1.0
80
[[1773    0]
 [   3    3]]
tp, tn, fp, fn:  (3, 1773, 0, 3)
train_score:  1.0
test_score:  0.9983136593591906
81
[[1777    0]
 [   0    2]]
tp, tn, fp, fn:  (2, 1777, 0, 0)
train_scor

In [59]:
print(len(e))
print(len(good_performance))

7115
136


In [60]:
for i in range(len(e.columns)):
    if e.iloc[2][i] == 1:
        print(i,e.columns[i])

52 정적스트레칭루틴프로그램


In [61]:
Jack = np.array([19.3,43.2,49.0,-10.0,36.0,88.0,11.1,149.8,2019.0,1.0,6.0,47.400,89.00,133.0])
Rose = np.array([18.5,48.7,47.0,-3.0,21.5,100.0,6.0,162.4,2019.0,1.0,13.0,47.400,91.00,139.0])
ME = np.array([22.5,66.3,26.0,-0.2,20.4,77.0,22.4,171.6,2019.0,1.0,15.0,46.2,112.0,122.0])
ME2 = np.array([20.5,64.3,40.0,-1.0,35.4,100.0,5.4,170.4,2019.0,1.0,12.0,43.6,119.0,130.0])
human = np.array([Jack, Rose, ME,ME2])

In [62]:
#.reshape(1,-1)
human = scaler.transform(human)

In [63]:
human

array([[-1.041, -1.173,  1.852, -0.529,  0.381,  0.698, -0.683, -0.887,
        -0.939,  0.716, -0.846,  0.829, -0.811,  0.665],
       [-1.175, -0.905,  1.674,  0.035, -1.042,  1.66 , -1.283,  0.09 ,
        -0.939,  0.716, -0.113,  0.829, -0.696,  1.059],
       [-0.505, -0.048, -0.196,  0.261, -1.15 , -0.183,  0.644,  0.802,
        -0.939,  0.716,  0.096,  0.642,  0.502, -0.057],
       [-0.84 , -0.145,  1.051,  0.196,  0.322,  1.66 , -1.353,  0.709,
        -0.939,  0.716, -0.218,  0.238,  0.901,  0.468]])

In [64]:
for i in range(len(E)):
    if (E[i].predict(human[3].reshape(1, -1))==1):
        print(e.columns[i]+" 운동이 필요합니다")

## train

In [65]:
for j in range(len(train)):
    #train = scaler.transform(train)
    for i in good_performance:
        if (m[i].predict(train[j].reshape(1, -1))==1):
            print(p.columns[i]+" 운동이 필요합니다")

KeyError: 0

In [ ]:
from sklearn.preprocessing import StandardScaler  
from sklearn.model_selection import train_test_split 
from imblearn.over_sampling import SMOTE
#from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score, precision_score, recall_score, matthews_corrcoef, plot_roc_curve, confusion_matrix
import xgboost as xgb

m = list()
for i in range(len(p.columns)):
    #smote = SMOTE(random_state=0)
    #train_over,label_over = smote.fit_sample(train,label[p.columns[i]])
    #print('SMOTE 적용 전 학습용 피처/레이블 데이터 세트: ', train.shape, label[p.columns[i]].shape)
    #print('SMOTE 적용 후 학습용 피처/레이블 데이터 세트: ', train_over.shape, label_over.shape)
    #print('SMOTE 적용 후 레이블 값 분포: \n', label_over.value_counts())
    train_features, test_features, train_labels, test_labels = train_test_split(train, label[p.columns[i]], stratify=label[p.columns[i]])
    scaler = StandardScaler()  
    train_features = scaler.fit_transform(train_features)  
    test_features = scaler.transform(test_features)
    
    dtrain = xgb.DMatrix(data = train_features, label = train_labels)
    dtest = xgb.DMatrix(data = test_features, label = test_labels)
    params = {
        "max_depth": 3, 
        "eta": 0.1, 
        "objective": "binary:logistic", 
        "eval_metric": "logloss"
        # "early_stoppings": 100 
        }

    num_rounds = 400 # 부스팅 반복 횟수

    # evals 파라미터에 train, test 셋을 명기하면 평가를 진행하면서 조기 중단을 적용 할 수 있다.
    wlist = [(dtrain, "train"), (dtest, "eval")]

    # 모델 학습: 사이킷런과 달리 train() 함수에 파라미터를 전달한다.
    xgb_model = xgb.train(params = params, dtrain = dtrain, num_boost_round = num_rounds,evals = wlist)
   
    #model = LogisticRegression()
    #model.fit(train_features, train_labels)
    y_pred = model.predict(test_features)
    
    f1 = f1_score(test_labels, y_pred)
    mcc_score = matthews_corrcoef(test_labels, y_pred)
    precision = precision_score(test_labels, y_pred)
    recall = recall_score(test_labels, y_pred)        
    auc_score = roc_auc_score(test_labels, y_pred)
    acc_score = accuracy_score(test_labels, y_pred)

    print(confusion_matrix(test_labels, y_pred))
    tn, fp, fn, tp = confusion_matrix(test_labels, y_pred).ravel()
    print('tp, tn, fp, fn: ', (tp, tn, fp, fn))
    print("train_score: ",model.score(train_features, train_labels))
    print("test_score: ",model.score(test_features, test_labels))
    m.append(xgb_model)

In [ ]:
# 예측 확률
for i in 
pred_probs = m[0].predict(dtest)
print("predict() 수행 결과값 10개만 표시")
print(np.round(pred_probs[:10], 3))

# 예측 분류
preds = [1 if x > 0.5 else 0 for x in pred_probs]
print("예측 분류 10개만 표시")
print(f"{preds[:10]}")

In [ ]:
train_features

In [ ]:
train = xgb.DMatrix(data = train_features[8:9], label = train_labels[8:9])

In [ ]:
train

In [ ]:
for i in range(243):
    if p.iloc[8][i] == 1:
        print(i,p.columns[i])

In [ ]:
Jack = np.array([19.3,43.2,49.0,-10.0,36.0,88.0,11.1,149.8,2019.0,1.0,6.0,47.400,89.00,133.0])
Rose = np.array([18.5,48.7,47.0,-3.0,21.5,100.0,6.0,162.4,2019.0,1.0,13.0,47.400,91.00,139.0])
ME = np.array([22.5,66.3,26.0,-0.2,20.4,77.0,22.4,171.6,2019.0,1.0,15.0,46.2,112.0,122.0])
human = np.array([Jack, Rose, ME])

#.reshape(1,-1)
human = scaler.transform(human)

human

for i in range(len(m)):
    if((m[i].predict(train))>0.5):
        print(p.columns[i]+" 운동이 필요합니다")

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.metrics import f1_score, roc_auc_score

def get_clf_eval(y_test, pred=None, pred_proba_po=None):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    auc = roc_auc_score(y_test, pred_proba_po)
   
    print("오차 행렬")
    print(confusion)
    print(f"정확도: {accuracy:.4f}, 정밀도: {precision:.4f}, 재현율: {recall:.4f}, F1: {f1:.4f}, AUC: {auc:.4f}")

In [ ]:
get_clf_eval(y_test, pred = preds, pred_proba_po = pred_probs)

In [ ]:
from xgboost import plot_importance

plot_importance(xgb_model)
plt.show()

In [ ]:
Jack = np.array([19.3,43.2,49.0,-10.0,36.0,88.0,11.1,149.8,2019.0,1.0,6.0,47.400,89.00,133.0])
Rose = np.array([18.5,48.7,47.0,-3.0,21.5,100.0,6.0,162.4,2019.0,1.0,13.0,47.400,91.00,139.0])
ME = np.array([22.5,66.3,26.0,-0.2,20.4,77.0,22.4,171.6,2019.0,1.0,15.0,46.2,112.0,122.0])
human = np.array([Jack, Rose, ME])

In [ ]:
#.reshape(1,-1)
human = scaler.transform(human)

In [ ]:
human

In [ ]:
for i in range(len(p.columns)):
    if (m[i].predict(human[1].reshape(1, -1))>0.8):
        print(p.columns[i]+" 운동이 필요합니다")

In [ ]:
m[1].predict(human[1].reshape(1, -1))

In [ ]:
m[100].predict(human[1].reshape(1, -1))

In [ ]:
for i in range(len(p.columns)):
    if (p.iloc[1][i] == 1):
        print(p.columns[i]+" 운동이 필요합니다")

In [ ]:
for i in range(268):
    if (m[i].predict(human[2].reshape(1, -1)) == 1):
        print(r.columns[i]+" 운동이 필요합니다")

In [ ]:
a = list()
a.append(float(input('BMI: ')))
a.append(float(input('Weight: ')))
a.append(float(input('age: ')))
a.append(float(input('bending_forward: ')))
a.append(float(input('body_fat: ')))
a.append(float(input('diastolic_bp: ')))
a.append(float(input('grip_power: ')))
a.append(float(input('height: ')))
a.append(float(input('sex: ')))
a.append(float(input('sit_up: ')))
a.append(float(input('systolic_bp: ')))

In [ ]:
for i in range(268):
    if (m[i].predict(np.array(a).reshape(1,-1) == 1)):
        print(r.columns[i]+" 운동이 필요합니다")